<?php
define(
    '_SQL_GRAVAR_USUARIO',
    "INSERT INTO USUARIO(NOME, SOBRENOME, EMAIL, SENHA)
    VALUES(?, ?, ?, MD5(?))"
);

define(
    '_SQL_LOGIN',
    "SELECT ID, NOME, SOBRENOME, EMAIL
    FROM USUARIO
    WHERE EMAIL = ? AND SENHA = MD5(?)"
);

define('_SQL_GRAVAR_CONTA',
"INSERT INTO CONTA(NOME, SALDO_INICIAL, SALDO, ID_USUARIO)
VALUES(?, ?, ?, ?)");

define('_SQL_GRAVAR_CATEGORIA',
"INSERT INTO CATEGORIA(NOME, TIPO, ID_USUARIO)
VALUES(?, ?, ?)");