<?php
define(
    '_SQL_GRAVAR_USUARIO',
    "INSERT INTO USUARIO(NOME, SOBRENOME, EMAIL, SENHA)
    VALUES(?, ?, ?, MD5(?))"
);

define(
    '_SQL_LOGIN',
    "SELECT ID, NOME, SOBRENOME, EMAIL
    FROM USUARIO
    WHERE EMAIL = ? AND SENHA = MD5(?)"
);

define('_SQL_GRAVAR_CONTA',
"INSERT INTO CONTA(NOME, DATA_CRIACAO, SALDO_INICIAL, SALDO, ID_USUARIO)
VALUES(?, CURRENT_DATE, ?, ?, ?)");

define('_SQL_GRAVAR_CATEGORIA',
"INSERT INTO CATEGORIA(NOME, TIPO, ID_USUARIO)
VALUES(?, ?, ?)");

define('_SQL_CARREGAR_CATEGORIAS',
"SELECT ID, NOME, TIPO
FROM CATEGORIA
WHERE ID_USUARIO = ?");

define('_SQL_CARREGAR_CONTAS',
"SELECT ID, NOME
FROM CONTA
WHERE ID_USUARIO = ?");

define('_SQL_GRAVAR_LANCAMENTO',
"INSERT INTO LANCAMENTO(TIPO, VALOR, DESCRICAO, DATA, ID_CATEGORIA, ID_CONTA, ID_USUARIO)
VALUES(?, ?, ?, ?, ?, ?, ?)");

define('_SQL_UPDATE_SALDO_CONTA_RECEITA',
"UPDATE CONTA
SET SALDO = SALDO + ?
WHERE ID = ?");

define('_SQL_UPDATE_SALDO_CONTA_DESPESA',
"UPDATE CONTA
SET SALDO = SALDO - ?
WHERE ID = ?");

define('_SQL_CARREGAR_SALDO_CONTAS',
"WITH RECEITAS AS (
	SELECT SUM(VALOR) VALOR_RECEITAS
    FROM LANCAMENTO
    WHERE TIPO = 'R'
    AND EXTRACT(YEAR_MONTH FROM DATA) <= ?
    AND ID_USUARIO = ?
),
DESPESAS AS (
	SELECT SUM(VALOR) VALOR_DESPESAS
    FROM LANCAMENTO
    WHERE TIPO = 'D'
    AND EXTRACT(YEAR_MONTH FROM DATA) <= ?
    AND ID_USUARIO = ?
)

SELECT
    (SELECT COALESCE(SUM(SALDO_INICIAL), 0) FROM CONTA WHERE ID_USUARIO = ? AND EXTRACT(YEAR_MONTH FROM DATA_CRIACAO) <= ?) +
    (SELECT COALESCE(VALOR_RECEITAS, 0) FROM RECEITAS) -
    (SELECT COALESCE(VALOR_DESPESAS, 0) FROM DESPESAS) AS SALDO_CONTAS");


define('_SQL_CARREGAR_RECEITAS_DESPESAS_BALANCO',
"WITH RECEITAS AS (
    SELECT SUM(VALOR) AS VALOR_RECEITAS
    FROM LANCAMENTO
    WHERE TIPO = 'R'
    AND EXTRACT(YEAR_MONTH FROM DATA) = ?
    AND ID_USUARIO = ?
),
DESPESAS AS (
    SELECT SUM(VALOR) AS VALOR_DESPESAS
    FROM LANCAMENTO
    WHERE TIPO = 'D'
    AND EXTRACT(YEAR_MONTH FROM DATA) = ?
    AND ID_USUARIO = ?
)

SELECT
    COALESCE(RECEITAS.VALOR_RECEITAS, 0) AS RECEITAS,
    COALESCE(DESPESAS.VALOR_DESPESAS, 0) AS DESPESAS,
    COALESCE(RECEITAS.VALOR_RECEITAS, 0) - COALESCE(DESPESAS.VALOR_DESPESAS, 0) AS BALANCO
FROM
    RECEITAS, DESPESAS;");